### ISSUE TITLE
Database:     Pick DB

### ISSUE THREAD

**Issue by bwingerd** [FearlessSolutions/BCDA-DPC-B2D2-Veteran-Attribution-API#55]

**Comment by nsaccente** [comment]
I would like to make an argument against using a relational database for this use case. Since FHIR is super extensible, creating an ERD to capture all possible extensions would be difficult, not to mention, time consuming to write parsers to convert ingested FHIR json into sql queries.

I suggest, instead, using a NoSQL database like mongo or couch, possibly in conjunction with Elasticsearch. This would also make it easier to serve back data, since we wouldn't have to convert it back to the FHIR spec.

**Comment by sb-keane** [comment]
We've went with postgres at least for job tracking and user management.
